config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  devise_for :users
  root 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :commenter, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.order("created_at DESC")
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])

  end

  def create
    @article = Article.new(article_params)
    @article.creator = current_user.id
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :creator)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :commenter_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title%>
    <%= f.text_field :title%>
  </div>


  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

    <div>
      <%= f.submit %>
    </div>


<% end %>

app/views/articles/edit.html.erb
<%= "Editing #{@article.title}" %>
<%= render "form" %>

app/views/articles/index.html.erb
<h1> Listing Articles </h1>
<%= link_to "New Article", new_article_path(@article) %>
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <%= link_to('Edit user', edit_user_registration_path) %>
    <% else %>
      <%= link_to('Login', new_user_session_path)  %>
    <% end %>

<div>
    <% @articles.each do |article| %>
      <% creator = User.find(article.creator) %>
      <h3><%= link_to article.title, article_path(article) %></h3>
      <p><%= simple_format(article.body) %></p><br>
      <% if article != @articles.last %>
      <hr />
      <% end %>
    <% end %>
  </div>

app/views/articles/new.html.erb
<h1> New Article </h1>
<%= render "form" %>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p><%= simple_format(@article.body) %></p>
<% if user_signed_in? && current_user.id == @article.creator %>
  <%= link_to "Edit Article", edit_article_path(@article) %>
  <%= link_to "Delete Article", @article, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <% if comment.commenter_id? %>
    <% commenter_user = User.find(comment.commenter_id) %>
    <%= link_to commenter_user.username %>
  <% else %>
    <%= comment.commenter %>
  <% end %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if user_signed_in? && current_user.id == @article.creator %>
 <%= link_to "Delete Comment", [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>

  <p>
    <% if user_signed_in? %>
      <%= f.hidden_field :commenter_id, value: current_user.id %>
      <%= f.hidden_field :commenter, value:  current_user.username%>
    <% else %>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    <% end %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Home</h1>
<%= link_to 'Blog', controller: 'articles' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nanoblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>